(feat)-update workflow github from xray

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,15 @@
 name: Java Selenium TestNG - Xray
 
 on:
-  push:
-    branches: [ main ]
-
   workflow_dispatch:
     inputs:
       testExecKey:
-        description: 'Test Exec ID from Xray'
-        default: ''
+        description: 'Test Execution key from Xray'
         required: true
         type: string
 
       projectKey:
-        description: 'Project ID from Xray'
-        default: ''
+        description: 'Jira/Xray project key'
         required: true
         type: string
 
@@ -24,21 +19,21 @@ jobs:
 
     steps:
 
-      # 1. Checkout projects
+      # 1. Checkout project
       - name: Checkout repository
         uses: actions/checkout@v4
 
 
       # 2. Setup Java 17
       - name: Setup Java 17
-        uses: actions/setup-java@v4
+        uses: actions/setup-java@v5
         with:
           distribution: temurin
           java-version: '17'
           cache: maven
 
 
-      # 3. Check Java and Mavenn
+      # 3. Check Java and Maven
       - name: Check Java and Maven
         run: |
           java -version
@@ -58,10 +53,29 @@ jobs:
         if: always()
         run: |
           echo "===== TestNG reports ====="
-          find target/surefire-reports -type f -maxdepth 2 || true
+          find target/surefire-reports -type f -maxdepth 2 -print || true
 
 
-      # 6. Import TestNG results into Xray
+      # 6. Check Xray secrets
+      - name: Check Xray secrets
+        if: always()
+        run: |
+          if [ -z "${{ secrets.XRAY_CLIENT_ID }}" ]; then
+            echo "ERROR: XRAY_CLIENT_ID is missing"
+            exit 1
+          else
+            echo "OK: XRAY_CLIENT_ID is available"
+          fi
+
+          if [ -z "${{ secrets.XRAY_CLIENT_SECRET }}" ]; then
+            echo "ERROR: XRAY_CLIENT_SECRET is missing"
+            exit 1
+          else
+            echo "OK: XRAY_CLIENT_SECRET is available"
+          fi
+
+
+      # 7. Import TestNG results into Xray
       - name: Import results to Xray
         if: always()
         uses: mikepenz/xray-action@v4
@@ -73,11 +87,11 @@ jobs:
 
           testPaths: "**/target/surefire-reports/testng-results.xml"
 
-          testExecKey: "${{ inputs.testExecKey }}"
-          projectKey: "${{ inputs.projectKey }}"
+          testExecKey: ${{ inputs.testExecKey }}
+          projectKey: ${{ inputs.projectKey }}
 
 
-      # 7. Save TestNG reports
+      # 8. Save TestNG reports
       - name: Upload TestNG reports
         if: always()
         uses: actions/upload-artifact@v4
